name: Build Flatpak

on:
  release:
    types: [created, published]
  push:
    branches:
      - main
      - ci-cd-automation
    paths:
      - 'flatpak/**'
      - '.github/workflows/build-flatpak.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:latest
    
    permissions:
      contents: write
      packages: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Build Flatpak
      uses: bilelmoussaoui/flatpak-github-actions/build@v6
      with:
        bundle: pywebsearch.flatpak
        manifest-path: flatpak/com.github.dmnmsc.pywebsearch.yml
        cache: false
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: pywebsearch-flatpak
        path: pywebsearch.flatpak
    
    - name: Upload to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: pywebsearch.flatpak
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
